// Auth
http://localhost:4000/api/users/currentuser
###
POST http://localhost:4000/api/users/signup HTTP/1.1
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password",
  "username": "rojasleon"
}
###
POST http://localhost:4000/api/users/signin HTTP/1.1
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}
###
POST http://localhost:4000/api/users/signout HTTP/1.1
###
PUT http://localhost:4000/api/users/rojasleon HTTP/1.1
Content-Type: application/json

{
  "username": "newrojasleon",
  "name": "Juan Luis Rojas León",
  "bio": "This is my bio"
}
###
http://localhost:4000/api/users/newrojasleon




# Products
###
http://localhost:4000/api/products

###
POST http://localhost:4000/api/products HTTP/1.1
Content-Type: application/json

{
  "name": "Toy bro",
  "price": 20,
  "description": "Enjoy like a kid"
}
###
PUT http://localhost:4000/api/products/1 HTTP/1.1
Content-Type: application/json

{
  "name": "A new product",
  "price": 15,
  "description": "This is a really good product"
}
###
http://localhost:4000/api/products/1

###
http://localhost:4000/api/search?term=laptop


# Wishlist
###
POST http://localhost:4000/api/wishlist HTTP/1.1
Content-Type: application/json

{
  "productId": 1
}
###
http://localhost:4000/api/wishlist





# Orders
###
POST http://localhost:4000/api/orders HTTP/1.1
Content-Type: application/json

{
  "productId": 1
}





# Cart

###
http://localhost:4000/api/cart
###
POST http://localhost:4000/api/cart HTTP/1.1
Content-Type: application/json

{
  "productId": 2,
  "quantity": 1
}




# Reviews
http://localhost:4000/api/reviews?productId=1
###
POST http://localhost:4000/api/reviews HTTP/1.1
Content-Type: application/json

{
  "productId": 1,
  "title": "Great product",
  "comment": "My life is better with this product, thanks",
  "score": 5
}
###
PUT http://localhost:4000/api/reviews/1 HTTP/1.1
Content-Type: application/json

{
  "productId": 1,
  "title": "Nevermind, the best",
  "comment": "Uffffff, sooo gooood",
  "score": 5
}





# Payments

###
POST http://localhost:4000/api/payments HTTP/1.1
Content-Type: application/json

{
  "token": "tok_visa",
  "orderId": 1
}